### ISSUE TITLE
同样需要原子性的textarea

### ISSUE THREAD

**Issue by ustczy** [uxcore/uxcore-textarea-form-field#8]
和input一样，需要原子性的textarea，这样才可以自己用原子性的组件去组合其它的form field，可以和input结合，用type区分是普通input还是textarea

**Comment by eternalsky** [comment]
可以使用 `<textarea className="kuma-textarea" />`

**Comment by ustczy** [comment]
如果只是需要一个样式 那kuma-textarea当然可以解决，问题是有些功能还是需要的呀

**Comment by eternalsky** [comment]
@ustczy 比如什么功能？
